In [3]:
import numpy as np
import pandas as pd
#import some library for model building

In [4]:
#read data
df = pd.read_csv("spam.csv")
df.head(10)

Label                                          EmailText
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [5]:
X = df["EmailText"]
Y = df["Label"]
print(X)
print("Y:")
print(Y)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568               Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: EmailText, Length: 5572, dtype: object
Y:
0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Label, Length: 5572, dtype: object


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=4)

In [7]:
#extract feature by counting # of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
features = cv.fit_transform(X_train)
feArry = features.toarray()
print(feArry[:5])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
from sklearn import svm
#create svm model

svmModel = svm.SVC()
svmModel.fit(features,y_train)

#test acurracy
#extract feature from text from x_test
features_test = cv.transform(X_test)

score = svmModel.score(features_test,y_test)
print(score)

0.9760765550239234


In [9]:
prediction = svmModel.predict(features_test)
from sklearn import metrics
my_matrix = metrics.confusion_matrix(y_test, prediction, labels=["spam","ham"])
print(my_matrix)

[[ 198   40]
 [   0 1434]]


In [10]:
# in kết quả để so sánh
#print(y_test)
y_test = np.array(y_test)
count = 0
for i in range(len(y_test)):
  if(y_test[i] != prediction[i]):
    count+=1
    print(y_test[i],prediction[i])

print(count)

spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
40


In [11]:
#trying with LogisticRegression Model
from sklearn.linear_model import LogisticRegression

lrModel = LogisticRegression(random_state=42).fit(features,y_train)
lrScore = lrModel.score(features_test,y_test)
print(lrScore)

lrY_predict = lrModel.predict(features_test)
print(lrY_predict[:5])
print(y_test[:5])

lrMetrics = metrics.confusion_matrix(y_test, lrY_predict, labels=["spam","ham"])
print(lrMetrics)

0.9784688995215312
['ham' 'ham' 'spam' 'ham' 'ham']
['ham' 'ham' 'spam' 'ham' 'ham']
[[ 204   34]
 [   2 1432]]


In [12]:
example = "12 hours left, free services. 50% off the improved Academia Premium. Gift yourself some back-to-school stress relief by upgrading to the best version ever of Academia Premium--at half the normal price."
example2 = "Hello geeks ,GATE 2022 is just a few weeks away! But worry not, we are here to help you!We bring to you yet another opportunity to strengthen your preparation and clear GATE-CS 2022 with flying colours."
example3 = "congrats! free money click in this link freemoney.com now or sms 9900 to get freemoney"
exArray = np.array([example,example2,example3])
print(exArray)

#extrace feature from text 
features_example = cv.transform(exArray)
exLR_predict = lrModel.predict(features_example)
print(exLR_predict)

exSVM_predict = svmModel.predict(features_example)
print(exSVM_predict)

['12 hours left, free services. 50% off the improved Academia Premium. Gift yourself some back-to-school stress relief by upgrading to the best version ever of Academia Premium--at half the normal price.'
 'Hello geeks ,GATE 2022 is just a few weeks away! But worry not, we are here to help you!We bring to you yet another opportunity to strengthen your preparation and clear GATE-CS 2022 with flying colours.'
 'congrats! free money click in this link freemoney.com now or sms 9900 to get freemoney']
['spam' 'ham' 'spam']
['ham' 'ham' 'spam']


In [13]:
#create RandomForest model to test
from sklearn.ensemble import RandomForestClassifier

#build model with fixed value to prevent large tree grown
rfModel = RandomForestClassifier(max_depth=500,random_state=4)
rfModel.fit(features,y_train)


rfScore = rfModel.score(features_test,y_test)
print(rfScore)

rf_predict = rfModel.predict(features_test)


y_test = np.array(y_test)
count = 0
for i in range(len(y_test)):
  if(y_test[i] != rf_predict[i]):
    count+=1
    print(y_test[i],rf_predict[i])
print(count)

0.9742822966507177
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
spam ham
43


In [14]:
#preprocessing data for Neural Network
from sklearn.preprocessing import LabelEncoder

X2 = df.EmailText
Y2 = df.Label
le = LabelEncoder()
Y2 = le.fit_transform(Y2) #ham and spam to 0 and 1
print(Y2)
Y2.reshape(-1,1)

[0 0 1 ... 0 0 0]


array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [15]:
X2_train, X2_test, Y2_train, Y2_test = train_test_split(X2, Y2, test_size=0.25, stratify = Y2)
print(X2_train[:2])
print(Y2_train[:2])

1039    They just talking thats it de. They wont any o...
2710    Hope you enjoyed your new content. text stop t...
Name: EmailText, dtype: object
[0 1]


In [16]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence

max_words = 1000
max_len = 150
tok = Tokenizer(num_words=max_words)
tok.fit_on_texts(X2_train)
sequences = tok.texts_to_sequences(X2_train)
sequences_matrix = sequence.pad_sequences(sequences,maxlen=max_len)

In [17]:
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.models import Model
def RNN():
    inputs = Input(name='inputs',shape=[max_len])
    layer = Embedding(max_words,128,input_length=max_len)(inputs)
    # Embedding (input_dim: size of vocabolary, 
    # output_dim: dimension of dense embedding, 
    # input_length: length of input sequence)
    layer = LSTM(64)(layer)
    layer = Dense(256,name='FC1')(layer)
    layer = Activation('relu')(layer)
    layer = Dropout(0.5)(layer)
    layer = Dense(1,name='out_layer')(layer)
    layer = Activation('sigmoid')(layer)
    model = Model(inputs=inputs,outputs=layer)
    return model

In [18]:
model = RNN()
model.summary()
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 inputs (InputLayer)         [(None, 150)]             0         
                                                                 
 embedding (Embedding)       (None, 150, 128)          128000    
                                                                 
 lstm (LSTM)                 (None, 64)                49408     
                                                                 
 FC1 (Dense)                 (None, 256)               16640     
                                                                 
 activation (Activation)     (None, 256)               0         
                                                                 
 dropout (Dropout)           (None, 256)               0         
                                                                 
 out_layer (Dense)           (None, 1)                 257   

In [19]:
model.fit(sequences_matrix,Y2_train, epochs=10,batch_size=128)

Epoch 1/10
33/33 [==============================] - 12s 276ms/step - loss: 0.4025 - accuracy: 0.8571
Epoch 2/10
33/33 [==============================] - 9s 273ms/step - loss: 0.0931 - accuracy: 0.9734
Epoch 3/10
33/33 [==============================] - 9s 273ms/step - loss: 0.0396 - accuracy: 0.9885
Epoch 4/10
33/33 [==============================] - 9s 273ms/step - loss: 0.0268 - accuracy: 0.9923
Epoch 5/10
33/33 [==============================] - 9s 272ms/step - loss: 0.0153 - accuracy: 0.9962
Epoch 6/10
33/33 [==============================] - 9s 274ms/step - loss: 0.0106 - accuracy: 0.9978
Epoch 7/10
33/33 [==============================] - 9s 275ms/step - loss: 0.0080 - accuracy: 0.9981
Epoch 8/10
33/33 [==============================] - 9s 278ms/step - loss: 0.0043 - accuracy: 0.9988
Epoch 9/10
33/33 [==============================] - 9s 279ms/step - loss: 0.0031 - accuracy: 0.9993
Epoch 10/10
33/33 [==============================] - 9s 276ms/step - loss: 0.0023 - accuracy: 0.999

In [20]:
test_sequences = tok.texts_to_sequences(X2_test)
test_sequences_matrix = sequence.pad_sequences(test_sequences,maxlen=max_len)

accr = model.evaluate(test_sequences_matrix,Y2_test)
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))

44/44 [==============================] - 2s 27ms/step - loss: 0.0901 - accuracy: 0.9856
Test set
  Loss: 0.090
  Accuracy: 0.986
